import raw from "@/data/csv/vulnerabilities.csv";
import { parseCsv, toBool, toNum, toOptional } from "./parse";
import type {
  BusinessCriticality,
  DataSensitivity,
  Environment,
  FindingType,
  Vulnerability,
  VulnerabilitySeverity,
  VulnerabilityStatus,
} from "@/types/vulnerability";

export function getVulnerabilities(): Vulnerability[] {
  const rows = parseCsv<Record<string, string>>(raw);
  return rows.map((r) => ({
    id: r.id,
    cve: r.cve,
    title: r.title,
    description: r.description,
    severity: r.severity as VulnerabilitySeverity,
    cvss: toNum(r.cvss),
    assetId: r.assetId,
    applicationId: r.applicationId,
    scanner: r.scanner,
    pluginId: r.pluginId,
    port: r.port ? toNum(r.port) : undefined,
    protocol: toOptional(r.protocol),
    firstSeen: r.firstSeen,
    lastSeen: r.lastSeen,
    status: r.status as VulnerabilityStatus,
    owner: toOptional(r.owner),
    dueDate: toOptional(r.dueDate),
    environment: r.environment as Environment,
    internetExposed: toBool(r.internetExposed),
    exploitAvailable: toBool(r.exploitAvailable),
    businessCriticality: r.businessCriticality as BusinessCriticality,
    dataSensitivity: r.dataSensitivity as DataSensitivity,
    riskScore: toNum(r.riskScore),
    epssScore: r.epssScore ? toNum(r.epssScore) : undefined,
    cwe: toOptional(r.cwe),
    isDuplicate: toBool(r.isDuplicate),
    parentFindingId: toOptional(r.parentFindingId),
    falsePositiveReason: toOptional(r.falsePositiveReason),
    affectedComponent: toOptional(r.affectedComponent),
    findingType: r.findingType as FindingType,
    apiId: toOptional(r.apiId),
    dependencyId: toOptional(r.dependencyId),
    assessmentType: toOptional(r.assessmentType),
    repository: toOptional(r.repository),
    branch: toOptional(r.branch),
    fileName: toOptional(r.fileName),
    lineNumber: r.lineNumber ? toNum(r.lineNumber) : undefined,
    codeSnippet: toOptional(r.codeSnippet),
    endpoint: toOptional(r.endpoint),
    httpMethod: toOptional(r.httpMethod),
    parameter: toOptional(r.parameter),
    requestSample: toOptional(r.requestSample),
    responseSample: toOptional(r.responseSample),
    packageName: toOptional(r.packageName),
    packageVersion: toOptional(r.packageVersion),
    ecosystem: toOptional(r.ecosystem),
    vulnerableVersion: toOptional(r.vulnerableVersion),
    fixedVersion: toOptional(r.fixedVersion),
    dependencyType: toOptional(r.dependencyType) as Vulnerability["dependencyType"],
    dependencyPath: toOptional(r.dependencyPath),
    license: toOptional(r.license),
  }));
}
